export const LANG = [
  {
    display: "EN",
    locale: "en-GB",
  },
  {
    display: "BM",
    locale: "ms-MY",
  },
  {
    display: "中",
    locale: "zh-CN",
  },
  {
    display: "த",
    locale: "ta-IN",
  },
];

export enum GEO_FILTER {
  District = "district",
  Mukim = "mukim",
  Parliament = "parliament",
  Assembly = "sla",
}

export enum STATES {
  JOHOR = "Johor",
  KEDAH = "Kedah",
  KELANTAN = "Kelantan",
  MELAKA = "Melaka",
  NEGERI_SEMBILAN = "Negeri Sembilan",
  PAHANG = "Pahang",
  PERAK = "Perak",
  PERLIS = "Perlis",
  PULAU_PINANG = "Pulau Pinang",
  SABAH = "Sabah",
  SARAWAK = "Sarawak",
  SELANGOR = "Selangor",
  TERRENGGAU = "Terengganu",
  KUALA_LUMPUR = "W.P. Kuala Lumpur",
  LABUAN = "W.P. Labuan",
  PUTRAJAYA = "W.P. Putrajaya",
}

export enum STATES_KEY {
  JOHOR = "jhr",
  KEDAH = "kdh",
  KELANTAN = "ktn",
  MELAKA = "mlk",
  NEGERI_SEMBILAN = "nsn",
  PAHANG = "phg",
  PERAK = "prk",
  PERLIS = "pls",
  PULAU_PINANG = "png",
  SABAH = "sbh",
  SARAWAK = "swk",
  SELANGOR = "sgr",
  TERRENGGAU = "trg",
  KUALA_LUMPUR = "kul",
  LABUAN = "lbn",
  PUTRAJAYA = "pjy",
}

export enum SNAPSHOT_COLUMNS {
  AreaType = "area_type",
  Area = "area",
  TotalPopulation = "total_population",
  TotalHouseholds = "total_households",
  // age_0_4_male,
  // age_5_9_male,
  // age_10_14_male,
  // age_15_19_male,
  // age_20_24_male,
  // age_25_29_male,
  // age_30_34_male,
  // age_35_39_male,
  // age_40_44_male,
  // age_45_49_male,
  // age_50_54_male,
  // age_55_59_male,
  // age_60_64_male,
  // age_65_69_male,
  // age_70_74_male,
  // age_75_79_male,
  // age_80_84_male,
  // age_85_above_male,
  // age_0_4_female,
  // age_5_9_female,
  // age_10_14_female,
  // age_15_19_female,
  // age_20_24_female,
  // age_25_29_female,
  // age_30_34_female,
  // age_35_39_female,
  // age_40_44_female,
  // age_45_49_female,
  // age_50_54_female,
  // age_55_59_female,
  // age_60_64_female,
  // age_65_69_female,
  // age_70_74_female,
  // age_75_79_female,
  // age_80_84_female,
  // age_85_above_female,
  Male = "sex_male",
  Female = "sex_female",
  Bumi = "ethnicity_bumi",
  Chinese = "ethnicity_chinese",
  Indian = "ethnicity_indian",
  OtherEthnicity = "ethnicity_other",
  Muslim = "religion_muslim",
  Christian = "religion_christian",
  Buddhist = "religion_buddhist",
  Hindu = "religion_hindu",
  Atheist = "religion_atheist",
  OtherReligion = "religion_other",
  Urban = "dev_urban",
  Rural = "dev_rural",
  Single = "marital_never_married",
  Married = "marital_married",
  Widowed = "marital_widowed",
  Divorced = "marital_divorced",
  Child = "agegroup_child",
  Working = "agegroup_working",
  Elderly = "agegroup_elderly",
}
