export const STATE_DISTRICT_MUKIM_MAPPING = {
  Johor: {
    "Batu Pahat": [
      "Mukim Bagan",
      "Mukim Chaah Bahru",
      "Mukim Kampung Bahru",
      "Mukim Linau",
      "Mukim Lubok",
      "Mukim Minyak Beku",
      "Mukim Peserai",
      "Mukim Simpang Kanan",
      "Mukim Simpang Kiri",
      "Mukim Sri Gading",
      "Mukim Sri Medan",
      "Mukim Sungai Kluang",
      "Mukim Sungai Punggor",
      "Mukim Tanjung Sembrong",
    ],
    "Johor Bahru": [
      "Bandar Johor Bahru",
      "Mukim Jelutong",
      "Mukim Plentong",
      "Mukim Pulai",
      "Mukim Sungai Tiram",
      "Mukim Tanjung Kupang",
      "Mukim Tebrau",
    ],
    Kluang: [
      "Mukim Kahang",
      "Mukim Kluang",
      "Mukim Layang-Layang",
      "Mukim Machap",
      "Mukim Niyor",
      "Mukim Paloh",
      "Mukim Rengam",
      "Mukim Ulu Benut",
    ],
    "Kota Tinggi": [
      "Mukim Johor Lama",
      "Mukim Kambau",
      "Mukim Kota Tinggi",
      "Mukim Pantai Timur",
      "Mukim Pengerang",
      "Mukim Sedili Besar",
      "Mukim Sedili Kechil",
      "Mukim Tanjung Surat",
      "Mukim Ulu Sungai Johor",
      "Mukim Ulu Sungei Sedili Besar",
    ],
    Kulai: ["Mukim Bukit Batu", "Mukim Kulai", "Mukim Sedenak", "Mukim Senai"],
    Mersing: [
      "Mukim Jemaluang",
      "Mukim Lenggor",
      "Mukim Mersing",
      "Mukim Padang Endau",
      "Mukim Penyabong",
      "Mukim Pulau Aur",
      "Mukim Pulau Babi",
      "Mukim Pulau Pemanggil",
      "Mukim Pulau Sibu",
      "Mukim Pulau Tinggi",
      "Mukim Sembrong",
      "Mukim Tenggaroh",
      "Mukim Tenglu",
      "Mukim Triang",
    ],
    Muar: [
      "Mukim Ayer Hitam",
      "Mukim Bandar",
      "Mukim Bukit Kepong",
      "Mukim Jalan Bakri",
      "Mukim Jorak",
      "Mukim Lenga",
      "Mukim Parit Bakar",
      "Mukim Parit Jawa",
      "Mukim Sri Menanti",
      "Mukim Sungai Balang",
      "Mukim Sungai Raya",
      "Mukim Sungai Terap",
    ],
    Pontian: [
      "Mukim Air Masin",
      "Mukim Api-Api",
      "Mukim Ayer Baloi",
      "Mukim Benut",
      "Mukim Jeram Batu",
      "Mukim Pengkalan Raja",
      "Mukim Pontian",
      "Mukim Rimba Terjun",
      "Mukim Serkat",
      "Mukim Sungai Karang",
      "Mukim Sungei Pinggan",
    ],
    Segamat: [
      "Mukim Bekok",
      "Mukim Buloh Kasap",
      "Mukim Chaah",
      "Mukim Gemas",
      "Mukim Gemereh",
      "Mukim Jabi",
      "Mukim Jementah",
      "Mukim Labis",
      "Mukim Pogoh",
      "Mukim Sermin",
      "Mukim Sungai Segamat",
    ],
    Tangkak: [
      "Mukim Bukit Serampang",
      "Mukim Grisek",
      "Mukim Kesang",
      "Mukim Kundang",
      "Mukim Serom",
      "Mukim Tangkak",
    ],
  },
  Kedah: {
    Baling: [
      "Mukim Bakai",
      "Mukim Baling",
      "Mukim Bongor",
      "Mukim Kupang",
      "Mukim Pulai",
      "Mukim Siong",
      "Mukim Tawar",
      "Mukim Teloi Kanan",
    ],
    "Bandar Baharu": [
      "Mukim Bagan Samak",
      "Mukim Kuala Selama",
      "Mukim Permatang Pasir",
      "Mukim Relau",
      "Mukim Serdang",
      "Mukim Sungai Batu",
      "Mukim Sungai Kechil",
    ],
    "Kota Setar": [
      "Mukim Alor Malai",
      "Mukim Anak Bukit",
      "Mukim Derga",
      "Mukim Gunong",
      "Mukim Kangkong",
      "Mukim Kubang Rotan",
      "Mukim Langgar",
      "Mukim Lengkuas",
      "Mukim Lepai",
      "Mukim Limbong",
      "Mukim Padang Hang",
      "Mukim Padang Lalang",
      "Mukim Pengkalan Kundor",
      "Mukim Sala Kechik",
      "Mukim Sungai Baharu",
      "Mukim Tajar",
      "Mukim Tebengau",
      "Mukim Telaga Mas",
      "Mukim Titi Gajah",
    ],
    "Kuala Muda": [
      "Mukim Bujang",
      "Mukim Bukit Meriam",
      "Mukim Gurun",
      "Mukim Haji Kudong",
      "Mukim Kota",
      "Mukim Kuala",
      "Mukim Merbok",
      "Mukim Pekula",
      "Mukim Pinang Tunggal",
      "Mukim Rantau Panjang",
      "Mukim Semeling",
      "Mukim Sidam Kiri",
      "Mukim Simpor",
      "Mukim Sungai Pasir",
      "Mukim Sungai Petani",
      "Mukim Teloi Kiri",
    ],
    "Kubang Pasu": [
      "Mukim Ah",
      "Mukim Binjal",
      "Mukim Bukit Tinggi",
      "Mukim Gelong",
      "Mukim Husba",
      "Mukim Jeram",
      "Mukim Jerlun",
      "Mukim Jitra",
      "Mukim Kepelu",
      "Mukim Kubang Pasu",
      "Mukim Malau",
      "Mukim Naga",
      "Mukim Padang Perahu",
      "Mukim Pelubang",
      "Mukim Pering",
      "Mukim Putat",
      "Mukim Sanglang",
      "Mukim Sungai Laka",
      "Mukim Temin",
      "Mukim Tunjang",
      "Mukim Wang Tepus",
    ],
    Kulim: [
      "Mukim Bagan Sena",
      "Mukim Junjong",
      "Mukim Karangan",
      "Mukim Kulim",
      "Mukim Mahang",
      "Mukim Naga Lilit",
      "Mukim Padang China",
      "Mukim Padang Meha",
      "Mukim Sedim",
      "Mukim Sidam Kanan",
      "Mukim Sungai Seluang",
      "Mukim Sungai Ular",
      "Mukim Terap",
    ],
    Langkawi: [
      "Bandar Kuah",
      "Mukim Ayer Hangat",
      "Mukim Bohor",
      "Mukim Kedawang",
      "Mukim Padang Mat Sirat",
      "Mukim Ulu Melaka",
    ],
    "Padang Terap": [
      "Mukim Batang Tunggang Kanan",
      "Mukim Batang Tunggang Kiri",
      "Mukim Belimbing Kanan",
      "Mukim Belimbing Kiri",
      "Mukim Kurong Hitam",
      "Mukim Padang Temak",
      "Mukim Padang Terap Kanan",
      "Mukim Padang Terap Kiri",
      "Mukim Pedu",
      "Mukim Tekai",
      "Mukim Tolak",
    ],
    Pendang: [
      "Mukim Ayer Puteh",
      "Mukim Bukit Paya",
      "Mukim Guar Kepayang",
      "Mukim Padang Kerbau",
      "Mukim Padang Peliang",
      "Mukim Padang Pusing",
      "Mukim Rambai",
      "Mukim Tobiar",
    ],
    "Pokok Sena": [
      "Mukim Bukit Lada",
      "Mukim Derang",
      "Mukim Gajah Mati",
      "Mukim Jabi",
      "Mukim Lesong",
      "Mukim Tualang",
    ],
    Sik: ["Mukim Jeneri", "Mukim Sik", "Mukim Sok"],
    Yan: [
      "Mukim Dulang",
      "Mukim Sala Besar",
      "Mukim Singkir",
      "Mukim Sungai Daun",
      "Mukim Yan",
    ],
  },
  Kelantan: {
    Bachok: [
      "Mukim Alor Bakat",
      "Mukim Bachok",
      "Mukim Bator",
      "Mukim Chap",
      "Mukim Cherang Hangus",
      "Mukim Gajah Mati",
      "Mukim Gunong",
      "Mukim Kemasin",
      "Mukim Kuau",
      "Mukim Kubang Telaga",
      "Mukim Kuchelong",
      "Mukim Lubok Tembesu",
      "Mukim Mak Lipah",
      "Mukim Melawi",
      "Mukim Nipah",
      "Mukim Pak Pura",
      "Mukim Pauh Sembilan",
      "Mukim Paya Mengkuang",
      "Mukim Perupok",
      "Mukim Repek",
      "Mukim Rusa",
      "Mukim Senak",
      "Mukim Serdang",
      "Mukim Takang",
      "Mukim Tanjong",
      "Mukim Tanjong Jering",
      "Mukim Tanjong Pauh",
      "Mukim Telok Mesira",
      "Mukim Telong",
      "Mukim Temu Ranggas",
      "Mukim Tepus",
      "Mukim Tualang Salak",
    ],
    "Gua Musang": [
      "Mukim Batu Papan",
      "Mukim Gua Musang",
      "Mukim Ketil",
      "Mukim Kuala Sungai",
      "Mukim Limau Kasturi",
      "Mukim Pulai",
      "Mukim Relai",
      "Mukim Renok",
      "Mukim Ulu Nenggiri",
    ],
    Jeli: [
      "Mukim Belimbing",
      "Mukim Bunga Tanjong",
      "Mukim Jeli",
      "Mukim Jeli Tepi Sungai",
      "Mukim Kalai",
      "Mukim Kuala Balah",
      "Mukim Lubok Bongor",
    ],
    "Kecil Lojing": [
      "Mukim Balar",
      "Mukim Blau",
      "Mukim Hau",
      "Mukim Hendrop",
      "Mukim Kuala Betis",
      "Mukim Sigar",
      "Mukim Tuel",
    ],
    "Kota Bharu": [
      "Bandar Kota Bharu",
      "Mukim Aur Duri",
      "Mukim Badak",
      "Mukim Badak Mati",
      "Mukim Badang",
      "Mukim Banggol",
      "Mukim Banggu",
      "Mukim Baung",
      "Mukim Bayang",
      "Mukim Bechah Mulong",
      "Mukim Beta Hilir",
      "Mukim Beta Hulu",
      "Mukim Beting",
      "Mukim Biah",
      "Mukim Binjai",
      "Mukim Buloh Poh",
      "Mukim Bunut Payong",
      "Mukim But",
      "Mukim Che Latiff",
      "Mukim Chekli",
      "Mukim Chekok",
      "Mukim Chicha",
      "Mukim Dal",
      "Mukim Demit",
      "Mukim Duson Rendah",
      "Mukim Guntong",
      "Mukim Jelutong",
      "Mukim Kadok",
      "Mukim Kampong Sireh",
      "Mukim Karang",
      "Mukim Kedai Buloh",
      "Mukim Kemubu",
      "Mukim Kemumin",
      "Mukim Kenali",
      "Mukim Ketereh Barat",
      "Mukim Ketereh Timor",
      "Mukim Kijang",
      "Mukim Koh",
      "Mukim Kota",
      "Mukim Langgar",
      "Mukim Lembu",
      "Mukim Lubok Jambu",
      "Mukim Lubok Pukol",
      "Mukim Lundang",
      "Mukim Lundang Paku",
      "Mukim Mahang Barat",
      "Mukim Mahang Timor",
      "Mukim Melor",
      "Mukim Mentuan",
      "Mukim Padang Bongor",
      "Mukim Padang Enggang",
      "Mukim Padang Garong",
      "Mukim Padang Leban",
      "Mukim Padang Raja",
      "Mukim Padang Sakar",
      "Mukim Padang Tengah",
      "Mukim Panchor",
      "Mukim Pangkal Pisang",
      "Mukim Parit",
      "Mukim Pasir Ha",
      "Mukim Pasir Mas",
      "Mukim Patek",
      "Mukim Pauh",
      "Mukim Paya",
      "Mukim Pendek",
      "Mukim Pengkalan Chepa",
      "Mukim Peringat",
      "Mukim Perol",
      "Mukim Pintu Gang",
      "Mukim Pulau",
      "Mukim Pulau Belanga",
      "Mukim Pulau Gajah",
      "Mukim Pulau Kundor",
      "Mukim Pulau Panjang",
      "Mukim Pulau Pisang",
      "Mukim Sabak",
      "Mukim Salor",
      "Mukim Semut Api",
      "Mukim Sering",
      "Mukim Seterpa",
      "Mukim Tanjong Chat",
      "Mukim Tapang",
      "Mukim Tebing Tinggi",
      "Mukim Telok",
      "Mukim Telok Bharu",
      "Mukim Telok Kitang",
      "Mukim Tiong",
      "Mukim Tok Ku",
      "Mukim Wakaf Siku",
      "Mukim Wakaf Stan",
    ],
    "Kuala Krai": [
      "Mukim Batu Mengkebang",
      "Mukim Enggong",
      "Mukim Gajah",
      "Mukim Kandek",
      "Mukim Kenor",
      "Mukim Kuala Geris",
      "Mukim Kuala Krai",
      "Mukim Kuala Nal",
      "Mukim Kuala Pahi",
      "Mukim Kuala Pergau",
      "Mukim Kuala Stong",
      "Mukim Mambong",
      "Mukim Manek Urai",
      "Mukim Manjor",
      "Mukim Telekong",
    ],
    Machang: [
      "Mukim Bagan",
      "Mukim Bakar",
      "Mukim Dewan",
      "Mukim Gading Galoh",
      "Mukim Jakar",
      "Mukim Joh",
      "Mukim Kelaweh",
      "Mukim Kerawang",
      "Mukim Kerilla",
      "Mukim Kuala Kerak",
      "Mukim Labok",
      "Mukim Limau Hantu",
      "Mukim Machang",
      "Mukim Padang Kemunchut",
      "Mukim Pek",
      "Mukim Pemanok",
      "Mukim Pulai Chondong",
      "Mukim Raja",
      "Mukim Temangan",
      "Mukim Tengah",
      "Mukim Tok Bok",
      "Mukim Ulu Sat",
    ],
    "Pasir Mas": [
      "Mukim Alor Buloh",
      "Mukim Alor Pasir",
      "Mukim Apa-Apa",
      "Mukim Apam",
      "Mukim Bakong",
      "Mukim Bechah Menerong",
      "Mukim Bechah Palas",
      "Mukim Bechah Semak",
      "Mukim Bukit Tuku",
      "Mukim Chetok",
      "Mukim Gelam",
      "Mukim Gua",
      "Mukim Gual Nering",
      "Mukim Gual Periok",
      "Mukim Jabo",
      "Mukim Jejawi",
      "Mukim Kala",
      "Mukim Kangkong",
      "Mukim Kasa",
      "Mukim Kedondong",
      "Mukim Kenak",
      "Mukim Kerasak",
      "Mukim Kiat",
      "Mukim Kuala Kelar",
      "Mukim Kuala Lemal",
      "Mukim Kubang Batang",
      "Mukim Kubang Bemban",
      "Mukim Kubang Gatal",
      "Mukim Kubang Gendang",
      "Mukim Kubang Ketam",
      "Mukim Kubang Sepat",
      "Mukim Kubang Terap",
      "Mukim Lalang",
      "Mukim Lubok Anching",
      "Mukim Lubok Gong",
      "Mukim Lubok Kawah",
      "Mukim Lubok Setol",
      "Mukim Lubok Tapah",
      "Mukim Meranti",
      "Mukim Padang Embon",
      "Mukim Paloh",
      "Mukim Rantau Panjang",
      "Mukim Sakar",
      "Mukim Tasik Berangan",
      "Mukim Teliar",
      "Mukim Tendong",
      "Mukim Tok Sangkot",
      "Mukim Tok Uban",
    ],
    "Pasir Puteh": [
      "Mukim Banggol Setol",
      "Mukim Batu Sebutir",
      "Mukim Berangan",
      "Mukim Bukit Abal Barat",
      "Mukim Bukit Abal Timor",
      "Mukim Bukit Merbau",
      "Mukim Bukit Tanah",
      "Mukim Changgai",
      "Mukim Cherang Ruku",
      "Mukim Gong Chapa",
      "Mukim Gong Chengal",
      "Mukim Gong Datok Barat",
      "Mukim Gong Datok Timor",
      "Mukim Gong Garu",
      "Mukim Gong Kulim",
      "Mukim Gong Nangka",
      "Mukim Gong Pachat",
      "Mukim Jeram",
      "Mukim Jerus",
      "Mukim Kampong Wakaf",
      "Mukim Kandis",
      "Mukim Kolam Tembesu",
      "Mukim Merbol",
      "Mukim Merkang",
      "Mukim Padang Pak Amat",
      "Mukim Pasir Puteh",
      "Mukim Pengkalan",
      "Mukim Permatang Sungkai",
      "Mukim Seligi",
      "Mukim Selising",
      "Mukim Semerak",
      "Mukim Tasik",
      "Mukim Telipok",
    ],
    "Tanah Merah": [
      "Mukim Batang Merbau",
      "Mukim Bendang Nyior",
      "Mukim Bukit Durian",
      "Mukim Jedok",
      "Mukim Kuala Paku",
      "Mukim Lawang",
      "Mukim Maka",
      "Mukim Nibong",
      "Mukim Pasir Ganda",
      "Mukim Rambai",
      "Mukim Sokor",
      "Mukim Tanah Merah",
      "Mukim Tebing Tinggi",
      "Mukim Ulu Kusial",
    ],
    Tumpat: [
      "Mukim Bechah Resak",
      "Mukim Bunohan",
      "Mukim Bunut Sarang Burong",
      "Mukim Chenderong Batu",
      "Mukim Cherang Melintang",
      "Mukim Geting",
      "Mukim Jal",
      "Mukim Kampong Laut",
      "Mukim Kelaboran",
      "Mukim Ketil",
      "Mukim Kok Keli",
      "Mukim Kutang",
      "Mukim Mak Neralang",
      "Mukim Morak",
      "Mukim Palekbang",
      "Mukim Pasir Pekan",
      "Mukim Periok",
      "Mukim Pulau Besar",
      "Mukim Selehong Selatan",
      "Mukim Selehong Utara",
      "Mukim Simpangan",
      "Mukim Sungai Pinang",
      "Mukim Tabar",
      "Mukim Talak",
      "Mukim Telok Renjuna",
      "Mukim Tujoh",
      "Mukim Tumpat",
      "Mukim Wakaf Bharu",
      "Mukim Wakaf Delima",
    ],
  },
  Melaka: {
    "Alor Gajah": [
      "Mukim Ayer Paabas",
      "Mukim Belimbing",
      "Mukim Beringin",
      "Mukim Brisu",
      "Mukim Durian Tunggal",
      "Mukim Gadek",
      "Mukim Kelemak",
      "Mukim Kemuning",
      "Mukim Kuala Linggi",
      "Mukim Kuala Sungei Baru",
      "Mukim Lendu",
      "Mukim Machap",
      "Mukim Malaka Pindah",
      "Mukim Masjid Tanah",
      "Mukim Melekek",
      "Mukim Padang Sebang",
      "Mukim Parit Melana",
      "Mukim Pegoh",
      "Mukim Pulau Sebang",
      "Mukim Ramuan China Besar",
      "Mukim Ramuan China Kechil",
      "Mukim Rembia",
      "Mukim Sungei Baru Ilir",
      "Mukim Sungei Baru Tengah",
      "Mukim Sungei Baru Ulu",
      "Mukim Sungei Buloh",
      "Mukim Sungei Petai",
      "Mukim Sungei Siput",
      "Mukim Taboh Naning",
      "Mukim Tanjong Rimau",
      "Mukim Tebong",
    ],
    Jasin: [
      "Mukim Ayer Panas",
      "Mukim Batang Malaka",
      "Mukim Bukit Senggeh",
      "Mukim Chabau",
      "Mukim Chin Chin",
      "Mukim Chohong",
      "Mukim Jasin",
      "Mukim Jus",
      "Mukim Kesang",
      "Mukim Merlimau",
      "Mukim Nyalas",
      "Mukim Rim",
      "Mukim Sebatu",
      "Mukim Selandar",
      "Mukim Sempang",
      "Mukim Semujok",
      "Mukim Serkam",
      "Mukim Sungei Rambai",
      "Mukim Tedong",
      "Mukim Umbai",
    ],
    "Melaka Tengah": [
      "Bandar Melaka",
      "Mukim Alai",
      "Mukim Ayer Molek",
      "Mukim Bachang",
      "Mukim Balai Panjang",
      "Mukim Batu Berendam",
      "Mukim Bertam",
      "Mukim Bukit Baru",
      "Mukim Bukit Katil",
      "Mukim Bukit Lintang",
      "Mukim Bukit Piatu",
      "Mukim Bukit Rambai",
      "Mukim Cheng",
      "Mukim Duyong",
      "Mukim Kandang",
      "Mukim Klebang Besar",
      "Mukim Klebang Kechil",
      "Mukim Krubong",
      "Mukim Padang Semabok",
      "Mukim Padang Temu",
      "Mukim Paya Rumput",
      "Mukim Pernu",
      "Mukim Pringgit",
      "Mukim Semabok",
      "Mukim Sungei Udang",
      "Mukim Tangga Batu",
      "Mukim Tanjong Kling",
      "Mukim Tanjong Minyak",
      "Mukim Telok Mas",
      "Mukim Ujong Pasir",
    ],
  },
  "Negeri Sembilan": {
    Jelebu: [
      "Mukim Glami Lemi",
      "Mukim Kenaboi",
      "Mukim Kuala Klawang",
      "Mukim Peradong",
      "Mukim Serting Ulu",
      "Mukim Triang Ilir",
      "Mukim Ulu Klawang",
      "Mukim Ulu Triang",
    ],
    Jempol: [
      "Mukim Jelai",
      "Mukim Kuala Jempol",
      "Mukim Rompin",
      "Mukim Serting Hilir",
    ],
    "Kuala Pilah": [
      "Mukim Ampang Tinggi",
      "Mukim Johol",
      "Mukim Juasseh",
      "Mukim Kepis",
      "Mukim Langkap",
      "Mukim Parit Tinggi",
      "Mukim Pilah",
      "Mukim Sri Menanti",
      "Mukim Terachi",
      "Mukim Ulu Jempol",
      "Mukim Ulu Muar",
    ],
    "Port Dickson": [
      "Mukim Jimah",
      "Mukim Linggi",
      "Mukim Pasir Panjang",
      "Mukim Port Dickson",
      "Mukim Si Rusa",
    ],
    Rembau: [
      "Mukim Batu Hampar",
      "Mukim Bongek",
      "Mukim Chembong",
      "Mukim Chengkau",
      "Mukim Gadong",
      "Mukim Kundor",
      "Mukim Legong Ilir",
      "Mukim Legong Ulu",
      "Mukim Miku",
      "Mukim Nerasau",
      "Mukim Pedas",
      "Mukim Pilin",
      "Mukim Selemak",
      "Mukim Semerbok",
      "Mukim Spri",
      "Mukim Tanjong Kling",
      "Mukim Titian Bintangor",
    ],
    Seremban: [
      "Mukim Ampangan",
      "Mukim Labu",
      "Mukim Lenggeng",
      "Mukim Pantai",
      "Mukim Rantau",
      "Mukim Rasah",
      "Mukim Seremban",
      "Mukim Setul",
    ],
    Tampin: [
      "Mukim Air Kuning",
      "Mukim Gemas",
      "Mukim Gemencheh",
      "Mukim Keru",
      "Mukim Repah",
      "Mukim Tampin Tengah",
      "Mukim Tebong",
    ],
  },
  Pahang: {
    Bentong: ["Mukim Bentong", "Mukim Pelangai", "Mukim Sabai"],
    Bera: ["Mukim Bera", "Mukim Triang"],
    "Cameron Highlands": [
      "Mukim Hulu Telom",
      "Mukim Ringlet",
      "Mukim Tanah Rata",
    ],
    Jerantut: [
      "Mukim Burau",
      "Mukim Hulu Cheka",
      "Mukim Hulu Tembeling",
      "Mukim Kelola",
      "Mukim Kuala Tembeling",
      "Mukim Pedah",
      "Mukim Pulau Tawar",
      "Mukim Tebing Tinggi",
      "Mukim Teh",
      "Mukim Tembeling",
    ],
    Kuantan: [
      "Mukim Beserah",
      "Mukim Hulu Kuantan",
      "Mukim Hulu Lepar",
      "Mukim Kuala Kuantan",
      "Mukim Penor",
      "Mukim Sungai Karang",
    ],
    Lipis: [
      "Mukim Batu Yon",
      "Mukim Budu",
      "Mukim Cheka",
      "Mukim Gua",
      "Mukim Hulu Jelai",
      "Mukim Kechau",
      "Mukim Kuala Lipis",
      "Mukim Penjom",
      "Mukim Tanjung Besar",
      "Mukim Telang",
    ],
    Maran: [
      "Mukim Bukit Segumpal",
      "Mukim Chenor",
      "Mukim Kertau",
      "Mukim Luit",
    ],
    Pekan: [
      "Mukim Bebar",
      "Mukim Ganchong",
      "Mukim Kuala Pahang",
      "Mukim Langgar",
      "Mukim Lepar",
      "Mukim Pahang Tua",
      "Mukim Pekan",
      "Mukim Penyor",
      "Mukim Pulau Manis",
      "Mukim Pulau Rusa",
      "Mukim Temai",
    ],
    Raub: [
      "Mukim Batu Talam",
      "Mukim Dong",
      "Mukim Gali",
      "Mukim Hulu Dong",
      "Mukim Sega",
      "Mukim Semantan Hulu",
      "Mukim Teras",
    ],
    Rompin: [
      "Mukim Endau",
      "Mukim Keratong",
      "Mukim Pontian",
      "Mukim Rompin",
      "Mukim Tioman",
    ],
    Temerloh: [
      "Mukim Bangau",
      "Mukim Jenderak",
      "Mukim Kerdau",
      "Mukim Lebak",
      "Mukim Lipat Kajang",
      "Mukim Mentakab",
      "Mukim Perak",
      "Mukim Sanggang",
      "Mukim Semantan",
      "Mukim Songsang",
    ],
  },
  Perak: {
    "Bagan Datuk": [
      "Mukim Bagan Datuk",
      "Mukim Hutan Melintang",
      "Mukim Rungkup",
      "Mukim Teluk Baru",
    ],
    "Batang Padang": [
      "Mukim Batang Padang",
      "Mukim Bidor",
      "Mukim Chenderiang",
      "Mukim Sungkai",
    ],
    "Hilir Perak": [
      "Mukim Changkat Jong",
      "Mukim Durian Sebatang",
      "Mukim Labu Kubong",
      "Mukim Sungai Durian",
      "Mukim Sungai Manik",
    ],
    "Hulu Perak": [
      "Mukim Belukar Semang",
      "Mukim Belum",
      "Mukim Durian Pipit",
      "Mukim Gerik",
      "Mukim Kenering",
      "Mukim Kerunai",
      "Mukim Lenggong",
      "Mukim Pengkalan Hulu",
      "Mukim Temelong",
      "Mukim Temengor",
    ],
    Kampar: ["Mukim Kampar", "Mukim Teja"],
    Kerian: [
      "Mukim Bagan Serai",
      "Mukim Bagan Tiang",
      "Mukim Beriah",
      "Mukim Gunong Semanggol",
      "Mukim Kuala Kurau",
      "Mukim Parit Buntar",
      "Mukim Selinsing",
      "Mukim Tanjong Piandang",
    ],
    Kinta: [
      "Mukim Belanja",
      "Mukim Hulu Kinta",
      "Mukim Sungai Raya",
      "Mukim Sungai Terap",
      "Mukim Tanjong Tualang",
    ],
    "Kuala Kangsar": [
      "Mukim Chegar Galah",
      "Mukim Kampong Buaya",
      "Mukim Kota Lama Kanan",
      "Mukim Kota Lama Kiri",
      "Mukim Lubok Merbau",
      "Mukim Pulau Kamiri",
      "Mukim Sayung",
      "Mukim Senggang",
      "Mukim Sungai Siput",
    ],
    "Larut Dan Matang": [
      "Mukim Asam Kumbang",
      "Mukim Batu Kurau",
      "Mukim Bukit Gantang",
      "Mukim Hulu Ijok",
      "Mukim Hulu Selama",
      "Mukim Jebong",
      "Mukim Kamunting",
      "Mukim Pengkalan Aor",
      "Mukim Selama",
      "Mukim Simpang",
      "Mukim Sungai Limau",
      "Mukim Sungai Tinggi",
      "Mukim Terung",
      "Mukim Tupai",
    ],
    Manjung: [
      "Mukim Beruas",
      "Mukim Lekir",
      "Mukim Lumut",
      "Mukim Pengkalan Baharu",
      "Mukim Sitiawan",
    ],
    Muallim: [
      "Mukim Hulu Bernam Barat",
      "Mukim Hulu Bernam Timur",
      "Mukim Slim",
    ],
    "Perak Tengah": [
      "Mukim Bandar",
      "Mukim Belanja",
      "Mukim Bota",
      "Mukim Jaya Baru",
      "Mukim Kampong Gajah",
      "Mukim Kota Setia",
      "Mukim Lambor Kanan",
      "Mukim Lambor Kiri",
      "Mukim Layang Layang",
      "Mukim Pasir Panjang Hulu",
      "Mukim Pasir Salak",
      "Mukim Pulau Tiga",
    ],
  },
  Perlis: {
    Perlis: [
      "Mukim Abi",
      "Mukim Arau",
      "Mukim Beseri",
      "Mukim Chuping",
      "Mukim Jejawi",
      "Mukim Kayang",
      "Mukim Kechor",
      "Mukim Kuala Perlis",
      "Mukim Kurong Anai",
      "Mukim Kurong Batang",
      "Mukim Ngulang",
      "Mukim Oran",
      "Mukim Padang Pauh",
      "Mukim Padang Siding",
      "Mukim Paya",
      "Mukim Sanglang",
      "Mukim Sena",
      "Mukim Seriab",
      "Mukim Sungai Adam",
      "Mukim Titi Tinggi",
      "Mukim Utan Aji",
      "Mukim Wang Bintong",
    ],
  },
  "Pulau Pinang": {
    "Barat Daya": [
      "Bandar Balik Pulau",
      "Mukim 1",
      "Mukim 10",
      "Mukim 11",
      "Mukim 12",
      "Mukim 2",
      "Mukim 3",
      "Mukim 4",
      "Mukim 5",
      "Mukim 6",
      "Mukim 7",
      "Mukim 8",
      "Mukim 9",
      "Mukim A",
      "Mukim B",
      "Mukim C",
      "Mukim D",
      "Mukim E",
      "Mukim F",
      "Mukim G",
      "Mukim H",
      "Mukim I",
      "Mukim J",
    ],
    "Seberang Perai Selatan": [
      "Mukim 1",
      "Mukim 10",
      "Mukim 11",
      "Mukim 12",
      "Mukim 13",
      "Mukim 14",
      "Mukim 15",
      "Mukim 16",
      "Mukim 2",
      "Mukim 3",
      "Mukim 4",
      "Mukim 5",
      "Mukim 6",
      "Mukim 7",
      "Mukim 8",
      "Mukim 9",
    ],
    "Seberang Perai Tengah": [
      "Bandar Bukit Mertajam",
      "Bandar Prai",
      "Mukim 1",
      "Mukim 10",
      "Mukim 11",
      "Mukim 12",
      "Mukim 13",
      "Mukim 14",
      "Mukim 15",
      "Mukim 16",
      "Mukim 17",
      "Mukim 18",
      "Mukim 19",
      "Mukim 2",
      "Mukim 20",
      "Mukim 21",
      "Mukim 3",
      "Mukim 4",
      "Mukim 5",
      "Mukim 6",
      "Mukim 7",
      "Mukim 8",
      "Mukim 9",
    ],
    "Seberang Perai Utara": [
      "Bandar Butterworth",
      "Bandar Kepala Batas",
      "Mukim 1",
      "Mukim 10",
      "Mukim 11",
      "Mukim 12",
      "Mukim 13",
      "Mukim 14",
      "Mukim 16",
      "Mukim 2",
      "Mukim 3",
      "Mukim 4",
      "Mukim 5",
      "Mukim 6",
      "Mukim 7",
      "Mukim 8",
      "Mukim 9",
    ],
    "Timur Laut": [
      "Bandar Ayer Itam",
      "Bandar Batu Ferringgi",
      "Bandar Bukit Bendera",
      "Bandar George Town",
      "Bandar Glugor",
      "Bandar Jelutong",
      "Bandar Tanjong Bungah",
      "Bandar Tanjong Pinang",
      "Mukim 13",
      "Mukim 14",
      "Mukim 15",
      "Mukim 16",
      "Mukim 17",
      "Mukim 18",
    ],
  },
  Sabah: {
    Beaufort: ["Beaufort"],
    Beluran: ["Beluran"],
    Kalabakan: ["Kalabakan"],
    Keningau: ["Keningau"],
    Kinabatangan: ["Kinabatangan"],
    "Kota Belud": ["Kota Belud"],
    "Kota Kinabalu": ["Kota Kinabalu"],
    "Kota Marudu": ["Kota Marudu"],
    "Kuala Penyu": ["Kuala Penyu"],
    Kudat: ["Kudat"],
    Kunak: ["Kunak"],
    "Lahad Datu": ["Lahad Datu"],
    Nabawan: ["Nabawan"],
    Papar: ["Papar"],
    Penampang: ["Penampang"],
    Pitas: ["Pitas"],
    Putatan: ["Putatan"],
    Ranau: ["Ranau"],
    Sandakan: ["Sandakan"],
    Semporna: ["Semporna"],
    Sipitang: ["Sipitang"],
    Tambunan: ["Tambunan"],
    Tawau: ["Tawau"],
    Telupid: ["Telupid"],
    Tenom: ["Tenom"],
    Tongod: ["Tongod"],
    Tuaran: ["Tuaran"],
  },
  Sarawak: {
    Asajaya: ["Sadong Land District"],
    Bau: ["Jagoi Land District", "Senggi-Poak Land District"],
    Belaga: [
      "Balui Land District",
      "Batu Laga Land District",
      "Danum Land District",
      "Mamau Land District",
      "Murum Land District",
      "Punan Land District",
    ],
    Beluru: [
      "Bakong Land District",
      "Bok Land District",
      "Dulit Land District",
      "Lepu Laju Land District",
      "Tinjar Land District",
    ],
    Betong: [
      "Batu Api Land District",
      "Entaban Land District",
      "Paku Land District",
      "Rimbas Land District",
      "Sadok Land District",
    ],
    Bintulu: ["Kemena Land District"],
    "Bukit Mabong": [
      "Baning Land District",
      "Entemu Land District",
      "Kumbong Land District",
      "Majau Land District",
      "Mengiong Land District",
      "Merirai Land District",
      "Oyan Land District",
      "Serani Land District",
      "Suau Land District",
    ],
    Dalat: ["Baoh Land District", "Oya-Dalat Land District"],
    Daro: ["Bruit Land District", "Semah Land District"],
    Julau: [
      "Jikang Land District",
      "Melurun Land District",
      "Tekoyong Land District",
    ],
    Kabong: ["Kalaka Land District", "Seblak Land District"],
    Kanowit: [
      "Lukut Land District",
      "Mapai Land District",
      "Maroh Land District",
      "Spali Land District",
    ],
    Kapit: [
      "Ibau Land District",
      "Menuan Land District",
      "Metah Land District",
      "Pelagus Land District",
      "Rirong Land District",
    ],
    Kuching: [
      "Kuching North Land District",
      "Kuching Town Land District",
      "Matang Land District",
      "Muara Tebas Land District",
      "Pangkalan Ampat Land District",
      "Salak Land District",
      "Sentah-Segu Land District",
      "Sentah-Segu Land District",
      "Sentah-Segu Land District",
    ],
    Lawas: [
      "Bakelalan Land District",
      "Lawas Land District",
      "Long Merarap Land District",
      "Long Semado Land District",
      "Merapok Land District",
      "Tengoa-Sukang Land District",
      "Trusan Land District",
    ],
    Limbang: [
      "Batu Lawi Land District",
      "Danau Land District",
      "Long Napir Land District",
      "Pandaruan Land District",
      "Sungai Adang Land District",
      "Sungai Medalam Land District",
    ],
    "Lubok Antu": [
      "Ai Engkari Land District",
      "Bukit Besai Land District",
      "Kranggas Land District",
      "Lemanak Land District",
      "Marup Land District",
      "Skrang Land District",
    ],
    Lundu: [
      "Gading Lundu Land District",
      "Pueh Land District",
      "Sampadi Land District",
      "Stungkor Land District",
    ],
    Maradong: [
      "Maradong Land District",
      "Seredeng Land District",
      "Tulai Land District",
    ],
    Marudi: [
      "Apoh Land District",
      "Kamunting Land District",
      "Puyut Land District",
      "Teraja Land District",
    ],
    Matu: [
      "Jemoreng Land District",
      "Lassa Land District",
      "Retus Land District",
    ],
    Miri: [
      "Bareo Land District",
      "Kuala Baram Land District",
      "Lambir Land District",
      "Lio Matoh Land District",
      "Miri Concession Land District",
    ],
    Mukah: [
      "Balingian Land District",
      "Bawan Land District",
      "Mukah Land District",
      "Sikat Land District",
    ],
    Pakan: ["Pedanum Land District"],
    Pusa: ["Sablor Land District", "Triso Land District"],
    Samarahan: [
      "Kuching Central Land District",
      "Muara Tuang Land District",
      "Samarahan Land District",
    ],
    Saratok: ["Awik-Krian Land District", "Budu Land District"],
    Sarikei: ["Sare Land District", "Sarikei Land District"],
    Sebauh: [
      "Batu Kapal Land District",
      "Binio Land District",
      "Jelalong Land District",
      "Lavang Land District",
      "Pandan Land District",
      "Rasan Land District",
      "Selezu Land District",
    ],
    Selangau: [
      "Arip Land District",
      "Buloh Land District",
      "Gigis Land District",
      "Lalai Land District",
      "Paku Land District",
      "Pelugau Land District",
      "Selangau Land District",
      "Spapa Land District",
    ],
    Serian: [
      "Bukar-Sadong Land District",
      "Melikin Land District",
      "Punda-Sabal  Land District",
      "Samarahan Land District",
      "Sedilu-Gedong Land District",
    ],
    Sibu: [
      "Assan Land District",
      "Engkilo Land District",
      "Kabang Land District",
      "Menyan Land District",
      "Pasai-Siong Land District",
      "Seduan Land District",
    ],
    Simunjan: [
      "Bukar-Sadong Land District",
      "Melikin Land District",
      "Menuku Land District",
      "Punda-Sabal  Land District",
      "Sebangan-Kepayang Land District",
      "Sedilu-Gedong Land District",
    ],
    Song: [
      "Angkuah Land District",
      "Bangkit Land District",
      "Katibas Land District",
      "Plandok Land District",
    ],
    "Sri Aman": [
      "Bijat Land District",
      "Klauh Land District",
      "Lesong Land District",
      "Selanjan Land District",
      "Silantek Land District",
      "Undup Land District",
    ],
    Subis: [
      "Bukit Kisi Land District",
      "Niah Land District",
      "Sawai Land District",
      "Sibuti Land District",
      "Suai Land District",
    ],
    "Tanjung Manis": ["Buan Land District", "Kedang Land District"],
    Tatau: [
      "Anap Land District",
      "Buan Land District",
      "Kakus Land District",
      "Sangan Land District",
    ],
    Tebedu: [
      "Kayan Land District",
      "Pangkalan Ampat Land District",
      "Sungai Kedup Land District",
    ],
    "Telang Usan": [
      "Akah Land District",
      "Patah Land District",
      "Silat Land District",
      "Telang Usang Land District",
      "Tutoh Land District",
    ],
  },
  Selangor: {
    Gombak: [
      "Bandar Selayang",
      "Mukim Batu",
      "Mukim Rawang",
      "Mukim Setapak",
      "Mukim Ulu Kelang",
    ],
    "Hulu Langat": [
      "Mukim Ampang",
      "Mukim Beranang",
      "Mukim Cheras",
      "Mukim Hulu Langat",
      "Mukim Kajang",
      "Mukim Semenyih",
      "Mukim Ulu Semenyih",
    ],
    "Hulu Selangor": [
      "Mukim Ampang Pechah",
      "Mukim Batang Kali",
      "Mukim Buloh Telor",
      "Mukim Kalumpang",
      "Mukim Kerling",
      "Mukim Kuala Kalumpang",
      "Mukim Peretak",
      "Mukim Rasa",
      "Mukim Serendah",
      "Mukim Sungai Gumut",
      "Mukim Sungai Tinggi",
      "Mukim Ulu Bernam",
      "Mukim Ulu Yam",
    ],
    Klang: ["Mukim Kapar", "Mukim Klang"],
    "Kuala Langat": [
      "Mukim Bandar",
      "Mukim Batu",
      "Mukim Jugra",
      "Mukim Kelanang",
      "Mukim Morib",
      "Mukim Tanjong Duabelas",
      "Mukim Telok Panglima Garang",
    ],
    "Kuala Selangor": [
      "Mukim Api-Api",
      "Mukim Bestari Jaya",
      "Mukim Ijok",
      "Mukim Jeram",
      "Mukim Kuala Selangor",
      "Mukim Pasangan",
      "Mukim Tanjong Karang",
      "Mukim Ujong Permatang",
      "Mukim Ulu Tinggi",
    ],
    Petaling: [
      "Mukim Bukit Raja",
      "Mukim Damansara",
      "Mukim Petaling",
      "Mukim Sungai Buloh",
    ],
    "Sabak Bernam": [
      "Mukim Bagan Nakhoda Omar",
      "Mukim Panchang Bedena",
      "Mukim Pasir Panjang",
      "Mukim Sabak",
      "Mukim Sungai Panjang",
    ],
    Sepang: ["Bandar Cyberjaya", "Mukim Dengkil", "Mukim Labu", "Mukim Sepang"],
  },
  Terengganu: {
    Besut: [
      "Mukim Bukit Kenak",
      "Mukim Bukit Peteri",
      "Mukim Hulu Besut",
      "Mukim Jabi",
      "Mukim Kampung Raja",
      "Mukim Keluang",
      "Mukim Kerandang",
      "Mukim Kuala Besut",
      "Mukim Kubang Bemban",
      "Mukim Lubuk Kawah",
      "Mukim Pangkalan Nangka",
      "Mukim Pasir Akar",
      "Mukim Pelagat",
      "Mukim Pulau Perhentian",
      "Mukim Tembila",
      "Mukim Tenang",
    ],
    Dungun: [
      "Mukim Besul",
      "Mukim Hulu Paka",
      "Mukim Jengai",
      "Mukim Jerangau",
      "Mukim Kuala Abang",
      "Mukim Kuala Dungun",
      "Mukim Kuala Paka",
      "Mukim Kumpal",
      "Mukim Pasir Raja",
      "Mukim Rasau",
      "Mukim Sura",
    ],
    "Hulu Terengganu": [
      "Mukim Hulu Berang",
      "Mukim Hulu Telemung",
      "Mukim Hulu Terengganu",
      "Mukim Jenagur",
      "Mukim Kuala Berang",
      "Mukim Kuala Telemung",
      "Mukim Penghulu Diman",
      "Mukim Tanggul",
      "Mukim Tersat",
    ],
    Kemaman: [
      "Mukim Bandi",
      "Mukim Banggul",
      "Mukim Binjai",
      "Mukim Cukai",
      "Mukim Hulu Cukai",
      "Mukim Hulu Jabur",
      "Mukim Kemasik",
      "Mukim Kertih",
      "Mukim Kijal",
      "Mukim Pasir Semut",
      "Mukim Tebak",
      "Mukim Teluk Kalung",
    ],
    "Kuala Nerus": [
      "Mukim Batu Rakit",
      "Mukim Kuala Nerus",
      "Mukim Pakoh",
      "Mukim Pulau Redang",
    ],
    "Kuala Terengganu": [
      "Mukim Atas Tol",
      "Mukim Batu Buruk",
      "Mukim Belara",
      "Mukim Bukit Besar",
      "Mukim Cabang Tiga",
      "Mukim Cenering",
      "Mukim Gelugur Kedai",
      "Mukim Gelugur Raja",
      "Mukim Kepung",
      "Mukim Kuala Ibai",
      "Mukim Kubang Parit",
      "Mukim Losong",
      "Mukim Manir",
      "Mukim Paluh",
      "Mukim Pengadang Buluh",
      "Mukim Pulau-Pulau",
      "Mukim Rengas",
      "Mukim Serada",
      "Mukim Tuk Jamal",
    ],
    Marang: [
      "Mukim Alur Limbat",
      "Mukim Bukit Payung",
      "Mukim Jerung",
      "Mukim Mercang",
      "Mukim Pulau Kerengga",
      "Mukim Rusila",
    ],
    Setiu: [
      "Mukim Caluk",
      "Mukim Guntung",
      "Mukim Hulu Nerus",
      "Mukim Hulu Setiu",
      "Mukim Merang",
      "Mukim Pantai",
      "Mukim Tasik",
    ],
  },
  "W.P. Kuala Lumpur": {
    "Kuala Lumpur": [
      "Bandar Kuala Lumpur",
      "Mukim Batu",
      "Mukim Kuala Lumpur",
      "Mukim Petaling",
      "Mukim Setapak",
    ],
  },
  "W.P. Labuan": { Labuan: ["Desa"] },
  "W.P. Putrajaya": { Putrajaya: ["Bandar Putrajaya"] },
};

export const STATE_PARLIAMENT_SLA_MAPPING = {
  Perlis: {
    "P.001 Padang Besar": [
      "N.01 Titi Tinggi",
      "N.02 Beseri",
      "N.03 Chuping",
      "N.04 Mata Ayer",
      "N.05 Santan",
    ],
    "P.002 Kangar": [
      "N.06 Bintong",
      "N.07 Sena",
      "N.08 Indera Kayangan",
      "N.09 Kuala Perlis",
      "N.10 Kayang",
    ],
    "P.003 Arau": [
      "N.11 Pauh",
      "N.12 Tambun Tulang",
      "N.13 Guar Sanji",
      "N.14 Simpang Empat",
      "N.15 Sanglang",
    ],
  },
  Kedah: {
    "P.004 Langkawi": ["N.01 Ayer Hangat", "N.02 Kuah"],
    "P.005 Jerlun": ["N.03 Kota Siputeh", "N.04 Ayer Hitam"],
    "P.006 Kubang Pasu": ["N.05 Bukit Kayu Hitam", "N.06 Jitra"],
    "P.007 Padang Terap": ["N.07 Kuala Nerang", "N.08 Pedu"],
    "P.008 Pokok Sena": ["N.09 Bukit Lada", "N.10 Bukit Pinang", "N.11 Derga"],
    "P.009 Alor Setar": [
      "N.12 Suka Menanti",
      "N.13 Kota Darul Aman",
      "N.14 Alor Mengkudu",
    ],
    "P.010 Kuala Kedah": [
      "N.15 Anak Bukit",
      "N.16 Kubang Rotan",
      "N.17 Pengkalan Kundor",
    ],
    "P.011 Pendang": ["N.18 Tokai", "N.19 Sungai Tiang"],
    "P.012 Jerai": ["N.20 Sungai Limau", "N.21 Guar Chempedak", "N.22 Gurun"],
    "P.013 Sik": ["N.23 Belantek", "N.24 Jeneri"],
    "P.014 Merbok": ["N.25 Bukit Selambau", "N.26 Tanjong Dawai"],
    "P.015 Sungai Petani": [
      "N.27 Pantai Merdeka",
      "N.28 Bakar Arang",
      "N.29 Sidam",
    ],
    "P.016 Baling": ["N.30 Bayu", "N.31 Kupang", "N.32 Kuala Ketil"],
    "P.017 Padang Serai": ["N.33 Merbau Pulas", "N.34 Lunas"],
    "P.018 Kulim-Bandar Baharu": ["N.35 Kulim", "N.36 Bandar Baharu"],
  },
  Kelantan: {
    "P.019 Tumpat": [
      "N.01 Pengkalan Kubor",
      "N.02 Kelaboran",
      "N.03 Pasir Pekan",
      "N.04 Wakaf Bharu",
    ],
    "P.020 Pengkalan Chepa": ["N.05 Kijang", "N.06 Chempaka", "N.07 Panchor"],
    "P.021 Kota Bharu": [
      "N.08 Tanjong Mas",
      "N.09 Kota Lama",
      "N.10 Bunut Payong",
    ],
    "P.022 Pasir Mas": ["N.11 Tendong", "N.12 Pengkalan Pasir", "N.13 Meranti"],
    "P.023 Rantau Panjang": [
      "N.14 Chetok",
      "N.15 Gual Periok",
      "N.16 Apam Putra",
    ],
    "P.024 Kubang Kerian": ["N.17 Salor", "N.18 Pasir Tumboh", "N.19 Demit"],
    "P.025 Bachok": ["N.20 Tawang", "N.21 Pantai Irama", "N.22 Jelawat"],
    "P.026 Ketereh": ["N.23 Melor", "N.24 Kadok", "N.25 Kok Lanas"],
    "P.027 Tanah Merah": [
      "N.26 Bukit Panau",
      "N.27 Gual Ipoh",
      "N.28 Kemahang",
    ],
    "P.028 Pasir Puteh": [
      "N.29 Selising",
      "N.30 Limbongan",
      "N.31 Semerak",
      "N.32 Gaal",
    ],
    "P.029 Machang": ["N.33 Pulai Chondong", "N.34 Temangan", "N.35 Kemuning"],
    "P.030 Jeli": ["N.36 Bukit Bunga", "N.37 Air Lanas", "N.38 Kuala Balah"],
    "P.031 Kuala Krai": [
      "N.39 Mengkebang",
      "N.40 Guchil",
      "N.41 Manek Urai",
      "N.42 Dabong",
    ],
    "P.032 Gua Musang": ["N.43 Nenggiri", "N.44 Paloh", "N.45 Galas"],
  },
  Terengganu: {
    "P.033 Besut": [
      "N.01 Kuala Besut",
      "N.02 Kota Putera",
      "N.03 Jertih",
      "N.04 Hulu Besut",
    ],
    "P.034 Setiu": [
      "N.05 Jabi",
      "N.06 Permaisuri",
      "N.07 Langkap",
      "N.08 Batu Rakit",
    ],
    "P.035 Kuala Nerus": [
      "N.09 Tepuh",
      "N.10 Buluh Gading",
      "N.11 Seberang Takir",
      "N.12 Bukit Tunggal",
    ],
    "P.036 Kuala Terengganu": [
      "N.13 Wakaf Mempelam",
      "N.14 Bandar",
      "N.15 Ladang",
      "N.16 Batu Buruk",
    ],
    "P.037 Marang": [
      "N.17 Alur Limbat",
      "N.18 Bukit Payung",
      "N.19 Ru Rendang",
      "N.20 Pengkalan Berangan",
    ],
    "P.038 Hulu Terengganu": [
      "N.21 Telemung",
      "N.22 Manir",
      "N.23 Kuala Berang",
      "N.24 Ajil",
    ],
    "P.039 Dungun": [
      "N.25 Bukit Besi",
      "N.26 Rantau Abang",
      "N.27 Sura",
      "N.28 Paka",
    ],
    "P.040 Kemaman": [
      "N.29 Kemasik",
      "N.30 Kijal",
      "N.31 Cukai",
      "N.32 Air Putih",
    ],
  },
  "Pulau Pinang": {
    "P.041 Kepala Batas": ["N.01 Penaga", "N.02 Bertam", "N.03 Pinang Tunggal"],
    "P.042 Tasek Gelugor": [
      "N.04 Permatang Berangan",
      "N.05 Sungai Dua",
      "N.06 Telok Ayer Tawar",
    ],
    "P.043 Bagan": [
      "N.07 Sungai Puyu",
      "N.08 Bagan Jermal",
      "N.09 Bagan Dalam",
    ],
    "P.044 Permatang Pauh": [
      "N.10 Seberang Jaya",
      "N.11 Permatang Pasir",
      "N.12 Penanti",
    ],
    "P.045 Bukit Mertajam": [
      "N.13 Berapit",
      "N.14 Machang Bubuk",
      "N.15 Padang Lalang",
    ],
    "P.046 Batu Kawan": [
      "N.16 Perai",
      "N.17 Bukit Tengah",
      "N.18 Bukit Tambun",
    ],
    "P.047 Nibong Tebal": [
      "N.19 Jawi",
      "N.20 Sungai Bakap",
      "N.21 Sungai Acheh",
    ],
    "P.048 Bukit Bendera": [
      "N.22 Tanjong Bunga",
      "N.23 Air Putih",
      "N.24 Kebun Bunga",
      "N.25 Pulau Tikus",
    ],
    "P.049 Tanjong": ["N.26 Padang Kota", "N.27 Pengkalan Kota", "N.28 Komtar"],
    "P.050 Jelutong": [
      "N.29 Datok Keramat",
      "N.30 Sungai Pinang",
      "N.31 Batu Lancang",
    ],
    "P.051 Bukit Gelugor": [
      "N.32 Seri Delima",
      "N.33 Air Itam",
      "N.34 Paya Terubong",
    ],
    "P.052 Bayan Baru": [
      "N.35 Batu Uban",
      "N.36 Pantai Jerejak",
      "N.37 Batu Maung",
    ],
    "P.053 Balik Pulau": [
      "N.38 Bayan Lepas",
      "N.39 Pulau Betong",
      "N.40 Telok Bahang",
    ],
  },
  Perak: {
    "P.054 Gerik": ["N.01 Pengkalan Hulu", "N.02 Temenggor"],
    "P.055 Lenggong": ["N.03 Kenering", "N.04 Kota Tampan"],
    "P.056 Larut": ["N.05 Selama", "N.06 Kubu Gajah", "N.07 Batu Kurau"],
    "P.057 Parit Buntar": ["N.08 Titi Serong", "N.09 Kuala Kurau"],
    "P.058 Bagan Serai": [
      "N.10 Alor Pongsu",
      "N.11 Gunong Semanggol",
      "N.12 Selinsing",
    ],
    "P.059 Bukit Gantang": [
      "N.13 Kuala Sepetang",
      "N.14 Changkat Jering",
      "N.15 Trong",
    ],
    "P.060 Taiping": ["N.16 Kamunting", "N.17 Pokok Assam", "N.18 Aulong"],
    "P.061 Padang Rengas": ["N.19 Chenderoh", "N.20 Lubok Merbau"],
    "P.062 Sungai Siput": ["N.21 Lintang", "N.22 Jalong"],
    "P.063 Tambun": ["N.23 Manjoi", "N.24 Hulu Kinta"],
    "P.064 Ipoh Timor": [
      "N.25 Canning",
      "N.26 Tebing Tinggi",
      "N.27 Pasir Pinji",
    ],
    "P.065 Ipoh Barat": ["N.28 Bercham", "N.29 Kepayang", "N.30 Buntong"],
    "P.066 Batu Gajah": ["N.31 Jelapang", "N.32 Menglembu", "N.33 Tronoh"],
    "P.067 Kuala Kangsar": ["N.34 Bukit Chandan", "N.35 Manong"],
    "P.068 Beruas": [
      "N.36 Pengkalan Baharu",
      "N.37 Pantai Remis",
      "N.38 Astaka",
    ],
    "P.069 Parit": ["N.39 Belanja", "N.40 Bota"],
    "P.070 Kampar": ["N.41 Malim Nawar", "N.42 Keranji", "N.42 Tualang Sekah"],
    "P.071 Gopeng": ["N.43 Sungai Rapat", "N.44 Simpang Pulai", "N.45 Teja"],
    "P.072 Tapah": ["N.46 Chenderiang", "N.47 Ayer Kuning"],
    "P.073 Pasir Salak": ["N.49 Sungai Manik", "N.50 Kampong Gajah"],
    "P.074 Lumut": ["N.51 Pasir Panjang", "N.52 Pangkor"],
    "P.075 Bagan Datuk": ["N.53 Rungkup", "N.54 Hutan Melintang"],
    "P.076 Teluk Intan": ["N.55 Pasir Bedamar", "N.56 Changkat Jong"],
    "P.077 Tanjung Malim": ["N.57 Sungkai", "N.58 Slim", "N.59 Behrang"],
  },
  Pahang: {
    "P.078 Cameron Highlands": ["N.01 Tanah Rata", "N.02 Jelai"],
    "P.079 Lipis": ["N.03 Padang Tengku", "N.04 Cheka", "N.05 Benta"],
    "P.080 Raub": ["N.06 Batu Talam", "N.07 Tras", "N.08 Dong"],
    "P.081 Jerantut": ["N.09 Tahan", "N.10 Damak", "N.11 Pulau Tawar"],
    "P.082 Indera Mahkota": ["N.12 Beserah", "N.13 Semambu"],
    "P.083 Kuantan": [
      "N.14 Teruntum",
      "N.15 Tanjung Lumpur",
      "N.16 Inderapura",
    ],
    "P.084 Paya Besar": ["N.17 Sungai Lembing", "N.18 Lepar", "N.19 Panching"],
    "P.085 Pekan": [
      "N.20 Pulau Manis",
      "N.21 Peramu Jaya",
      "N.22 Bebar",
      "N.23 Chini",
    ],
    "P.086 Maran": ["N.24 Luit", "N.25 Kuala Sentul", "N.26 Chenor"],
    "P.087 Kuala Krau": ["N.27 Jenderak", "N.28 Kerdau", "N.29 Jengka"],
    "P.088 Temerloh": ["N.30 Mentakab", "N.31 Lanchang", "N.32 Kuala Semantan"],
    "P.089 Bentong": [
      "N.33 Bilut",
      "N.34 Ketari",
      "N.35 Sabai",
      "N.36 Pelangai",
    ],
    "P.090 Bera": ["N.37 Guai", "N.38 Triang", "N.39 Kemayan"],
    "P.091 Rompin": ["N.40 Bukit Ibam", "N.41 Muadzam Shah", "N.42 Tioman"],
  },
  Selangor: {
    "P.092 Sabak Bernam": ["N.01 Sungai Air Tawar", "N.02 Sabak"],
    "P.093 Sungai Besar": ["N.03 Sungai Panjang", "N.04 Sekinchan"],
    "P.094 Hulu Selangor": [
      "N.05 Hulu Bernam",
      "N.06 Kuala Kubu Baharu",
      "N.07 Batang Kali",
    ],
    "P.095 Tanjong Karang": ["N.08 Sungai Burong", "N.09 Permatang"],
    "P.096 Kuala Selangor": ["N.10 Bukit Melawati", "N.11 Ijok", "N.12 Jeram"],
    "P.097 Selayang": ["N.13 Kuang", "N.14 Rawang", "N.15 Taman Templer"],
    "P.098 Gombak": [
      "N.16 Sungai Tua",
      "N.17 Gombak Setia",
      "N.18 Hulu Kelang",
    ],
    "P.099 Ampang": ["N.19 Bukit Antarabangsa", "N.20 Lembah Jaya"],
    "P.100 Pandan": ["N.21 Pandan Indah", "N.22 Teratai"],
    "P.101 Hulu Langat": ["N.23 Dusun Tua", "N.24 Semenyih", "N.25 Kajang"],
    "P.102 Bangi": [
      "N.26 Sungai Ramal",
      "N.27 Balakong",
      "N.28 Seri Kembangan",
    ],
    "P.103 Puchong": ["N.29 Seri Serdang", "N.30 Kinrara"],
    "P.104 Subang": ["N.31 Subang Jaya", "N.32 Seri Setia"],
    "P.105 Petaling Jaya": ["N.33 Taman Medan", "N.34 Bukit Gasing"],
    "P.106 Damansara": ["N.35 Kampung Tunku", "N.36 Bandar Utama"],
    "P.107 Sungai Buloh": [
      "N.37 Bukit Lanjan",
      "N.38 Paya Jaras",
      "N.39 Kota Damansara",
    ],
    "P.108 Shah Alam": ["N.40 Kota Anggerik", "N.41 Batu Tiga"],
    "P.109 Kapar": ["N.42 Meru", "N.43 Sementa", "N.44 Selat Klang"],
    "P.110 Klang": [
      "N.45 Bandar Baru Klang",
      "N.46 Pelabuhan Klang",
      "N.47 Pandamaran",
    ],
    "P.111 Kota Raja": [
      "N.48 Sentosa",
      "N.49 Sungai Kandis",
      "N.50 Kota Kemuning",
    ],
    "P.112 Kuala Langat": ["N.51 Sijangkang", "N.52 Banting", "N.53 Morib"],
    "P.113 Sepang": ["N.54 Tanjong Sepat", "N.55 Dengkil", "N.56 Sungai Pelek"],
  },
  "W.P. Kuala Lumpur": {
    "P.114 Kepong": [""],
    "P.115 Batu": [""],
    "P.116 Wangsa Maju": [""],
    "P.117 Segambut": [""],
    "P.118 Setiawangsa": [""],
    "P.119 Titiwangsa": [""],
    "P.120 Bukit Bintang": [""],
    "P.121 Lembah Pantai": [""],
    "P.122 Seputeh": [""],
    "P.123 Cheras": [""],
    "P.124 Bandar Tun Razak": [""],
  },
  "W.P. Putrajaya": { "P.125 Putrajaya": [""] },
  "Negeri Sembilan": {
    "P.126 Jelebu": [
      "N.01 Chennah",
      "N.02 Pertang",
      "N.03 Sungai Lui",
      "N.04 Klawang",
    ],
    "P.127 Jempol": [
      "N.05 Serting",
      "N.06 Palong",
      "N.07 Jeram Padang",
      "N.08 Bahau",
    ],
    "P.128 Seremban": [
      "N.09 Lenggeng",
      "N.10 Nilai",
      "N.11 Lobak",
      "N.12 Temiang",
      "N.13 Sikamat",
    ],
    "P.129 Kuala Pilah": [
      "N.15 Juasseh",
      "N.16 Seri Menanti",
      "N.17 Senaling",
      "N.18 Pilah",
      "N.19 Johol",
    ],
    "P.130 Rasah": [
      "N.20 Labu",
      "N.21 Bukit Kepayang",
      "N.22 Rahang",
      "N.23 Mambau",
      "N.24 Seremban Jaya",
    ],
    "P.131 Rembau": ["N.25 Paroi", "N.26 Chembong", "N.27 Rantau", "N.28 Kota"],
    "P.132 Port Dickson": [
      "N.29 Chuah",
      "N.30 Lukut",
      "N.31 Bagan Pinang",
      "N.32 Linggi",
      "N.33 Sri Tanjung",
    ],
    "P.133 Tampin": ["N.34 Gemas", "N.35 Gemencheh", "N.36 Repah"],
  },
  Melaka: {
    "P.134 Masjid Tanah": [
      "N.01 Kuala Linggi",
      "N.02 Tanjung Bidara",
      "N.03 Ayer Limau",
      "N.04 Lendu",
      "N.05 Taboh Naning",
    ],
    "P.135 Alor Gajah": [
      "N.06 Rembia",
      "N.07 Gadek",
      "N.08 Machap Jaya",
      "N.09 Durian Tunggal",
      "N.10 Asahan",
    ],
    "P.136 Tangga Batu": [
      "N.11 Sungai Udang",
      "N.12 Pantai Kundor",
      "N.13 Paya Rumput",
      "N.14 Kelebang",
    ],
    "P.137 Hang Tuah Jaya": [
      "N.15 Pengkalan Batu",
      "N.16 Ayer Keroh",
      "N.17 Bukit Katil",
      "N.18 Ayer Molek",
    ],
    "P.138 Kota Melaka": [
      "N.19 Kesidang",
      "N.20 Kota Laksamana",
      "N.21 Duyong",
      "N.22 Bandar Hilir",
      "N.23 Telok Mas",
    ],
    "P.139 Jasin": [
      "N.24 Bemban",
      "N.25 Rim",
      "N.26 Serkam",
      "N.27 Merlimau",
      "N.28 Sungai Rambai",
    ],
  },
  Johor: {
    "P.140 Segamat": ["N.01 Buloh Kasap", "N.02 Jementah"],
    "P.141 Sekijang": ["N.03 Pemanis", "N.04 Kemelah"],
    "P.142 Labis": ["N.05 Tenang", "N.06 Bekok"],
    "P.143 Pagoh": ["N.07 Bukit Kepong", "N.08 Bukit Pasir"],
    "P.144 Ledang": ["N.09 Gambir", "N.10 Tangkak", "N.11 Serom"],
    "P.145 Bakri": ["N.12 Bentayan", "N.13 Simpang Jeram", "N.14 Bukit Naning"],
    "P.146 Muar": ["N.15 Maharani", "N.16 Sungai Balang"],
    "P.147 Parit Sulong": ["N.17 Semerah", "N.18 Sri Medan"],
    "P.148 Ayer Hitam": ["N.19 Yong Peng", "N.20 Semarang"],
    "P.149 Sri Gading": ["N.21 Parit Yaani", "N.22 Parit Raja"],
    "P.150 Batu Pahat": ["N.23 Penggaram", "N.24 Senggarang", "N.25 Rengit"],
    "P.151 Simpang Renggam": ["N.26 Machap", "N.27 Layang-Layang"],
    "P.152 Kluang": ["N.28 Mengkibol", "N.29 Mahkota"],
    "P.153 Sembrong": ["N.30 Paloh", "N.31 Kahang"],
    "P.154 Mersing": ["N.32 Endau", "N.33 Tenggaroh"],
    "P.155 Tenggara": ["N.34 Panti", "N.35 Pasir Raja"],
    "P.156 Kota Tinggi": ["N.36 Sedili", "N.37 Johor Lama"],
    "P.157 Pengerang": ["N.38 Penawar", "N.39 Tanjung Surat"],
    "P.158 Tebrau": ["N.40 Tiram", "N.41 Puteri Wangsa"],
    "P.159 Pasir Gudang": ["N.42 Johor Jaya", "N.43 Permas"],
    "P.160 Johor Bahru": ["N.44 Larkin", "N.45 Stulang"],
    "P.161 Pulai": ["N.46 Perling", "N.47 Kempas"],
    "P.162 Iskandar Puteri": ["N.48 Skudai", "N.49 Kota Iskandar"],
    "P.163 Kulai": ["N.50 Bukit Permai", "N.51 Bukit Batu", "N.52 Senai"],
    "P.164 Pontian": ["N.53 Benut", "N.54 Pulai Sebatang"],
    "P.165 Tanjung Piai": ["N.55 Pekan Nanas", "N.56 Kukup"],
  },
  "W.P. Labuan": { "P.166 Labuan": [""] },
  Sabah: {
    "P.167 Kudat": [
      "N.01 Banggi",
      "N.02 Bengkoka",
      "N.03 Pitas",
      "N.04 Tanjong Kapor",
    ],
    "P.168 Kota Marudu": ["N.05 Matunggong", "N.06 Bandau", "N.07 Tandek"],
    "P.169 Kota Belud": [
      "N.08 Pintasan",
      "N.09 Tempasuk",
      "N.10 Usukan",
      "N.11 Kadamaian",
    ],
    "P.170 Tuaran": [
      "N.12 Sulaman",
      "N.13 Pantai Dalit",
      "N.14 Tamparuli",
      "N.15 Kiulu",
    ],
    "P.171 Sepanggar": ["N.16 Karambunai", "N.17 Darau", "N.18 Inanam"],
    "P.172 Kota Kinabalu": ["N.19 Likas", "N.20 Api-Api", "N.21 Luyang"],
    "P.173 Putatan": [
      "N.22 Tanjong Aru",
      "N.23 Petagas",
      "N.24 Tanjung Keramat",
    ],
    "P.174 Penampang": ["N.25 Kapayan", "N.26 Moyog"],
    "P.175 Papar": ["N.27 Limbahau", "N.28 Kawang", "N.29 Pantai Manis"],
    "P.176 Kimanis": ["N.30 Bongawan", "N.31 Membakut"],
    "P.177 Beaufort": ["N.32 Klias", "N.33 Kuala Penyu"],
    "P.178 Sipitang": ["N.34 Lumadan", "N.35 Sindumin"],
    "P.179 Ranau": ["N.36 Kundasang", "N.37 Karanaan", "N.38 Paginatan"],
    "P.180 Keningau": ["N.39 Tambunan", "N.40 Bingkor", "N.41 Liawan"],
    "P.181 Tenom": ["N.42 Melalap", "N.43 Kemabong"],
    "P.182 Pensiangan": ["N.44 Tulid", "N.45 Sook", "N.46 Nabawan"],
    "P.183 Beluran": ["N.47 Telupid", "N.48 Sugut", "N.49 Labuk"],
    "P.184 Libaran": [
      "N.50 Gum-Gum",
      "N.51 Sungai Manila",
      "N.52 Sungai Sibuga",
    ],
    "P.185 Batu Sapi": ["N.53 Sekong", "N.54 Karamunting"],
    "P.186 Sandakan": ["N.55 Elopura", "N.56 Tanjong Papat"],
    "P.187 Kinabatangan": ["N.57 Kuamut", "N.58 Lamag", "N.59Sukau"],
    "P.188 Lahad Datu": [
      "N.60 Tungku",
      "N.61 Segama",
      "N.62 Silam",
      "N.63 Kunak",
    ],
    "P.189 Semporna": ["N.64 Sulabayan", "N.65 Senallang", "N.66 Bugaya"],
    "P.190 Tawau": ["N.67 Balung", "N.68 Apas", "N.69 Sri Tanjong"],
    "P.191 Kalabakan": [
      "N.70 Kukusan",
      "N.71 Tanjung Batu",
      "N.72 Merotai",
      "N.73 Sebatik",
    ],
  },
  Sarawak: {
    "P.192 Mas Gading": ["N.01 Opar", "N.02 Tasik Biru"],
    "P.193 Santubong": [
      "N.03 Tanjong Datu",
      "N.04 Pantai Damai",
      "N.05 Demak Laut",
    ],
    "P.194 Petra Jaya": ["N.06 Tupong", "N.07 Samariang", "N.08 Satok"],
    "P.195 Bandar Kuching": [
      "N.09 Padungan",
      "N.10 Pending",
      "N.11 Batu Lintang",
    ],
    "P.196 Stampin": [
      "N.12 Kota Sentosa",
      "N.13 Batu Kitang",
      "N.14 Batu Kawah",
    ],
    "P.197 Kota Samarahan": ["N.15 Asajaya", "N.16 Muara Tuang", "N.17 Stakan"],
    "P.198 Puncak Borneo": ["N.18 Serembu", "N.19 Mambong", "N.20 Tarat"],
    "P.199 Serian": ["N.21 Tebedu", "N.22 Kedup", "N.23 Bukit Semuja"],
    "P.200 Batang Sadong": ["N.25 Sadong Jaya", "N.25 Simunjan", "N.26 Gedong"],
    "P.201 Batang Lupar": ["N.27 Sebuyau", "N.28 Lingga", "N.29 Beting Maro"],
    "P.202 Sri Aman": [
      "N.30 Balai Ringin",
      "N.31 Bukit Begunan",
      "N.32 Simanggang",
    ],
    "P.203 Lubok Antu": ["N.33 Engkilili", "N.34 Batang Ai"],
    "P.204 Betong": ["N.35 Saribas", "N.36 Layar", "N.37 Bukit Saban"],
    "P.205 Saratok": ["N.38 Kalaka", "N.39 Krian", "N.40 Kabong"],
    "P.206 Tanjong Manis": ["N.41 Kuala Rajang", "N.42 Semop"],
    "P.207 Igan": ["N.43 Daro", "N.44 Jemoreng"],
    "P.208 Sarikei": ["N.45 Repok", "N.46 Meradong"],
    "P.209 Julau": ["N.47 Pakan", "N.48 Meluan"],
    "P.210 Kanowit": ["N.49 Ngemah", "N.50 Machan"],
    "P.211 Lanang": ["N.51 Bukit Assek", "N.52 Dudong"],
    "P.212 Sibu": ["N.53 Bawang Assan", "N.54 Pelawan", "N.55 Nangka"],
    "P.213 Mukah": ["N.56 Dalat", "N.57 Tellian", "N.58 Balingian"],
    "P.214 Selangau": ["N.59 Tamin", "N.60 Kakus"],
    "P.215 Kapit": ["N.61 Pelagus", "N.62 Katibas", "N.63 Bukit Goram"],
    "P.216 Hulu Rajang": ["N.64 Baleh", "N.65 Belaga", "N.66 Murum"],
    "P.217 Bintulu": [
      "N.67 Jepak",
      "N.68 Tanjong Batu",
      "N.69 Kemena",
      "N.70 Samalaju",
    ],
    "P.218 Sibuti": ["N.71 Bekenu", "N.72 Lambir"],
    "P.219 Miri": ["N.73 Piasau", "N.74 Pujut", "N.75 Senadin"],
    "P.220 Baram": ["N.76 Marudi", "N.77 Telang Usan", "N.78 Mulu"],
    "P.221 Limbang": ["N.79 Bukit Kota", "N.80 Baru Danau"],
    "P.222 Lawas": ["N.81 Ba'kelalan", "N.82 Bukit Sari"],
  },
};
